### PR TITLE
initializeAnt implementation

### PR DESCRIPTION
**Pull request by eylulyalcinkaya**

### CODE REVIEW

**Review by PedroH-Reis — COMMENTED** [review]
Eylul, we talked in the meeting about the branches, I forget to said it to you =(.

we are going to create the feature branchs and merge it into develop.

when we have a MVP, at least, we can merge into main, makes sense?

**Comment by eylulyalcinkaya** [comment]
@PedroH-Reis
definitely makes sense, I changed the base to develop

**Comment by PedroH-Reis** [comment]
> @PedroH-Reis
> definitely makes sense, I changed the base to develop

**Comment by PedroH-Reis** [comment]
> @PedroH-Reis
> definitely makes sense, I changed the base to develop

Ok, btw I changed the base branch to develop (I forgot to do this earlier)

**Pull request merged**
